services:

    app.register_controller:
        class: AppBundle\Infrastructure\Controller\RegisterController
        arguments: [@command_bus, @event_bus, @form.factory, @templating, @app.user_query]

    app.register_user_command_handler:
        class: AppBundle\Core\Register\Handler\RegisterUserCommandHandler
        arguments: [@app.user_manager]
        tags:
            - { name: command_handler, handles: AppBundle\Core\Register\Command\RegisterUserCommand }

    app.user_manager:
        class: AppBundle\Core\User\Manager\UserManager
        arguments: [@app.user_repository]

    app.user_repository_file:
        class: AppBundle\Core\User\Persistence\FileUserRepository

    app.user_repository:
        alias: app.user_repository_file

    app.fake_queue:
        class: AppBundle\Infrastructure\MessageQueue\FakeQueue

    app.middleware:
        class: AppBundle\Infrastructure\CommandBus\CommandBusMiddleware
        arguments: [@app.fake_queue]
        public: false
        tags:
            - { name: command_bus_middleware, priority: 100 }
            - { name: event_bus_middleware, priority: 100 }

    app.user_registered_crm_event_subscriber:
        class: AppBundle\Core\Register\EventSubscriber\CRMSubscriber
        arguments: [@command_bus]
        tags:
            - { name: event_subscriber, subscribes_to: AppBundle\Core\Register\Command\RegisterUserCommand }

    app.user_query_file:
        class: AppBundle\Core\User\Query\FileUserQuery

    app.user_query:
        alias: app.user_query_file